#!/usr/bin/bash

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
sudo ufw allow 22
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo "Hello World!" | /var/www/html/index.nginx-debian.html
