#!/usr/bin/env bash
#Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
sudo ufw allow 22
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo "Hello World!" | /var/www/html/index.nginx-debian.html
