#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes.
hour=0
while [[ $hour -le 12 ]]
do
	echo "Hour: $hour"
	min=0
	while [[ $min -le 60 ]]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
